apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: kube-gateway
data:
  traefik.toml: |
    [entryPoints]
      [entryPoints.web]
          address = ":80"
      [entryPoints.websecure]
          address = ":443"
      [entryPoints.metrics]
          address = ":8082"
    [certificatesResolvers.myresolver.acme]
      email = "yinshengphy@gmail.com"
      storage = "acme.json"
      caserver = "https://acme-v02.api.letsencrypt.org/directory"
      tlsChallenge = true
    [api]
      dashboard = true
      insecure = true
    [providers.kubernetesCRD]
    [metrics]
      [metrics.prometheus]
        buckets=[0.1,0.3,1.2,5.0]
        entryPoint = "metrics"
    [accessLog]