kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik
  namespace: kube-gateway
  labels:
    k8s-app: traefik-ingress-lb
spec:
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      tolerations:
        - operator: "Exists"
      containers:
        - image: traefik:v2.2
          name: traefik-ingress-lb
          ports:
            - name: web
              containerPort: 80
              hostPort: 80
            - name: websecure
              containerPort: 443
              hostPort: 443
            - name: admin
              containerPort: 8080
            - name: metrics
              containerPort: 8082
          volumeMounts:
            - mountPath: "/etc/traefik"
              name: config
      volumes:
        - name: config
          configMap:
            name: traefik-config
---

kind: Service
apiVersion: v1
metadata:
  name: traefik
  namespace: kube-gateway
spec:
  selector:
    k8s-app: traefik-ingress-lb
  ports:
    - protocol: TCP
      port: 8080
      name: admin
    - protocol: TCP
      port: 8082
      name: metrics