kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: drone-pvc
  namespace: kube-ops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: course-nfs-storage