kind: Service
apiVersion: v1
metadata:
  name: yinshengphy-cn
  namespace: nginx
  labels:
    app: yinshengphy-cn
spec:
  selector:
    app: yinshengphy-cn
  clusterIP: None
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yinshengphy-cn
  namespace: nginx
  labels:
    app: yinshengphy-cn
spec:
  selector:
    matchLabels:
      app: yinshengphy-cn # has to match .spec.template.metadata.labels
  serviceName: "yinshengphy-cn"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: yinshengphy-cn # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: yinshengphy-cn
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: www
        namespace: nginx
      spec:
        accessModes: [ "ReadWriteOnce" ]
        #        storageClassName: "my-storage-class"*
        resources:
          requests:
            storage: 1Gi