kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-core
  namespace: monitoring
apiVersion: v1
data:
  prometheus.yaml: |
    global:
        scrape_interval: 15s
        scrape_timeout: 15s
        evaluation_interval: 15s
    scrape_configs:
    - job_name: 'traefik'
      static_configs:
        - targets: ['traefik.kube-gateway.svc.cluster.local:8082']
    - job_name: 'kube-state'
      static_configs:
        - targets: ['kube-state-metrics.monitoring.svc.cluster.local:8080']
    - job_name: 'node-exporter'
      static_configs:
        - targets: ['prometheus-node-exporter.monitoring.svc.cluster.local:9100']